FROM jenkins/jenkins:lts
USER root
RUN apt-get update && apt-get install -y --no-install-recommends \
  systemd \
  apt-transport-https \
  ca-certificates \
  curl \
  gnupg2 \
  software-properties-common 

RUN curl -fsSL https://get.docker.com -o get-docker.sh \
    && sh get-docker.sh \
    && usermod -aG docker jenkins 

USER jenkins
